version: '3'

services:
  app:
    restart: always
    image: "${HOOD_ENGINE_IMAGE}"
    ports:
      - "5050:5050"
    command: >
      sh -c "python3 engine.py"
    env_file:
      - ./.env
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - ./.env
    ports:
     - "3306:3306"
    volumes: 
      - ./db:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
    volumes:
    - ./redis-volume:/data
  celery:
    restart: always
    image: "${HOOD_ENGINE_IMAGE}"
    command: celery -A celery_worker worker -l info
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
volumes:
  db: